spring:
  application:
    name: security
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/security-example
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /security
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  jwt:
    secret-key: dkssudgktpdywjsmsqkrtjdgusdlqslek

server:
  port: 8899
  servlet:
    session:
      timeout: 1m

logging:
  level:
    org:
      springframework:
        security: DEBUG